"""Add created_at and updated_at defaults

Revision ID: 5a3aad65635a
Revises: 941b0584567a
Create Date: 2024-10-09 00:11:51.805616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a3aad65635a'
down_revision: Union[str, None] = '941b0584567a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('affiliate_stats', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('affiliate_stats', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('affiliate_stats', 'updated_at')
    op.drop_column('affiliate_stats', 'created_at')
    # ### end Alembic commands ###
