"""updated relationships within User, Transaction, and AffiliateStats

Revision ID: 6ef34ba0f03a
Revises: de23282cfc73
Create Date: 2024-10-09 18:26:58.480792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6ef34ba0f03a'
down_revision: Union[str, None] = 'de23282cfc73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('affiliate_stats', sa.Column('affiliate_sales', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('affiliate_stats', 'affiliate_sales')
    # ### end Alembic commands ###
