"""removed AffiliateStats table

Revision ID: 7e03a8700bf4
Revises: 7369f4654cfc
Create Date: 2024-10-22 09:54:05.687540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e03a8700bf4'
down_revision: Union[str, None] = '7369f4654cfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('affiliate_stats')
    op.drop_constraint('transactions_affiliate_id_fkey', 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'affiliate_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('affiliate_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('transactions_affiliate_id_fkey', 'transactions', 'affiliate_stats', ['affiliate_id'], ['id'])
    op.create_table('affiliate_stats',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('affiliate_sales', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='affiliate_stats_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='affiliate_stats_pkey')
    )
    # ### end Alembic commands ###
