"""removed randomTestColumn to AffiliateStats

Revision ID: de23282cfc73
Revises: 0983d4d17709
Create Date: 2024-10-09 17:13:07.230731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de23282cfc73'
down_revision: Union[str, None] = '0983d4d17709'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('affiliate_stats', 'randomTestColumn')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('affiliate_stats', sa.Column('randomTestColumn', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
