"""removed user relationship within Transaction table

Revision ID: fd4126fe4b73
Revises: 1ef91a1709dc
Create Date: 2024-10-11 09:45:57.952161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd4126fe4b73'
down_revision: Union[str, None] = '1ef91a1709dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
